apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "daemons.redhat.com/v1alpha1",
          "kind": "TangServer",
          "metadata": {
            "finalizers": [
              "finalizer.daemons.tangserver.redhat.com"
            ],
            "name": "tangserver",
            "namespace": "nbde"
          },
          "spec": {
            "healthScript": "/usr/bin/tangd-health-check",
            "image": "registry.redhat.io/rhel9/tang",
            "keyPath": "/var/db/tang",
            "persistentVolumeClaim": "tangserver-pvc",
            "replicas": 1,
            "version": "latest"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-10-03T10:18:36Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: nbde-tang-server.v1.0.11
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TangServer is the Schema for the tangservers API
      displayName: Tang Server
      kind: TangServer
      name: tangservers.daemons.redhat.com
      resources:
      - kind: Deployment
        version: v1
      - kind: ReplicaSet
        version: v1
      - kind: Pod
        version: v1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      specDescriptors:
      - description: ClusterIP
        displayName: ClusterIP (empty by default)
        path: clusterIP
      - description: HealthScript is the script to run for healthiness/readiness
        displayName: Health Script to execute
        path: healthScript
      - description: HiddenKeys
        displayName: Hidden Keys contains a list with the keys (with sha1 or sha256)
          to hide
        path: hiddenKeys
      - description: Image is the base container image of the TangServer to use
        displayName: Image of Container to deploy
        path: image
      - description: KeyPath is field of TangServer. It allows to specify the path
          where keys will be generated
        displayName: Key Path
        path: keyPath
      - description: KeyRefreshInterval
        displayName: Refresh Interval to update key status
        path: keyRefreshInterval
      - description: Persistent Volume Claim to store the keys
        displayName: Persistent Volume Claim to attach to (default:tangserver-pvc)
        path: persistentVolumeClaim
      - description: PodListenPort is the port where pods will listen for traffic
        displayName: 'Port where Pod will listen '
        path: podListenPort
      - description: Replicas is the Tang Server amount to bring up
        displayName: Amount of replicas to launch
        path: replicas
      - description: RequiredActiveKeyPairs
        displayName: Required Active Key Pairs (1 by default)
        path: requiredActiveKeyPairs
      - description: ResourceLimit is the resource limit to perform for each pod
        displayName: Resources Limit for Tang Server
        path: resourcesLimit
      - description: ResourceRequest is the resource request to perform for each pod
        displayName: Resources Request for Tang Server
        path: resourcesRequest
      - description: Secret is the secret name to use to download image appropriately
        displayName: Secret name to use for container download
        path: secret
      - description: ServiceListenPort is the port where service will listen for traffic
        displayName: Port where service will listen
        path: serviceListenPort
      - description: ServiceType
        displayName: ServiceType (LoadBalancer by default)
        path: serviceType
      - description: Version is the version of the TangServer container to use (empty=>latest)
        displayName: Image Version of Container to deploy
        path: version
      statusDescriptors:
      - description: ActiveKeys provides information about the Active Keys in the
          Tang Server CR
        displayName: Tang Server Active Keys
        path: activeKeys
        x-descriptors:
        - urn:alm:descriptor:text
      - description: FileName provides information about the file name corresponding
          to the key
        displayName: Active Key file name
        path: activeKeys[0].fileName
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Active Key Generation Time
        displayName: Active Key Generation Time
        path: activeKeys[0].generated
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Active Key sha1
        displayName: Active Key SHA1
        path: activeKeys[0].sha1
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Active Key sha256
        displayName: Active Key SHA256
        path: activeKeys[0].sha256
        x-descriptors:
        - urn:alm:descriptor:text
      - description: HiddenKeys provides information about the Hidden Keys in the
          Tang Server CR
        displayName: Tang Server Hidden Keys
        path: hiddenKeys
        x-descriptors:
        - urn:alm:descriptor:text
      - description: FileName provides information about the file name corresponding
          to the key
        displayName: Hidden Key file name
        path: hiddenKeys[0].fileName
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Hidden Key Hiding Time
        displayName: Hidden Key Generation Time
        path: hiddenKeys[0].generated
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Hidden Key Generation Time
        displayName: Hidden Key Hidden Time
        path: hiddenKeys[0].hidden
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Hidden Key sha1
        displayName: Hidden Key SHA1
        path: hiddenKeys[0].sha1
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Hidden Key sha256
        displayName: Hidden Key SHA256
        path: hiddenKeys[0].sha256
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Tang Server Ready provides information about the Ready Replicas
        displayName: Tang Server Ready Replicas
        path: ready
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Tang Server Running provides information about the Running Replicas
        displayName: Tang Server Running Replicas
        path: running
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Tang Server Service External URL provides information about the
          External Service URL
        displayName: Tang Server External URL
        path: serviceExternalURL
        x-descriptors:
        - urn:alm:descriptor:text
      - description: TangServerError collects error on Tang Operator creation
        displayName: Tang Server Error
        path: tangServerError
        x-descriptors:
        - urn:alm:descriptor:text
      version: v1alpha1
  description: NBDE Tang Server operator
  displayName: nbde-tang-server
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/log
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/status
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - daemons.redhat.com
          resources:
          - tangservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - daemons.redhat.com
          resources:
          - tangservers/finalizers
          verbs:
          - update
        - apiGroups:
          - daemons.redhat.com
          resources:
          - tangservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: nbde-tang-server-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: nbde-tang-server-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                - --http2-disable
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/sarroutb/nbde-tang-server:v1.0.11
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 400Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: nbde-tang-server-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: nbde-tang-server-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nbde
  - tang
  - server
  - security
  links:
  - name: NBDE Tang Server
    url: https://github.com/openshift/nbde-tang-server
  maintainers:
  - email: sarroutb@redhat.com
    name: Sergio Arroutbi Braojos
  - email: scorreia@redhat.com
    name: Sergio Correia
  maturity: alpha
  provider:
    name: Red Hat Openshift
    url: https://github.com/openshift/nbde-tang-server
  version: 1.0.11
