---
# permissions for end users to edit tangservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tangserver-editor-role
rules:
- apiGroups:
  - nbde.openshift.io
  resources:
  - tangservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nbde.openshift.io
  resources:
  - tangservers/status
  verbs:
  - get
