---
apiVersion: nbde.openshift.io/v1alpha1
kind: TangServer
metadata:
  name: tangserver
  namespace: nbde
  finalizers:
  - finalizer.nbde.tangserver.openshift.io
spec:
  # Add fields here
  keyPath: /var/db/tang
  persistentVolumeClaim: tangserver-pvc
  replicas: 1
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  healthScript: "/usr/bin/tangd-health-check"
