kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: cross-compile
spec:
  params: [ ]
  tasks:
    - name: cross-compile
      taskSpec:
        volumes:
          - name: source
            emptyDir: { }
        steps:
          - image: docker.io/library/golang:1.23.3
            env:
              - name: URL
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/source-repo-url']
              - name: REVISION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/sha']
            computeResources:
              limits:
                cpu: 8
                memory: 4Gi
              requests:
                cpu: 500m
                memory: 1Gi
            volumeMounts:
              - name: source
                mountPath: /workspace
            script: |
              #!/bin/bash
              set -ex
              archs="386 arm amd64 arm64 mips mipsle mips64 mips64le ppc64 ppc64le riscv64 s390x"
              if [ -z "$URL" ] || [ -z "$REVISION" ]; then
                echo "URL and REVISION not set ... no component?"
                exit 0
              fi
              echo "Initializing the env vars"
              echo "URL: $URL"
              echo "REVISION: $REVISION"
              mkdir /workspace/source
              cd /workspace/source
              git init
              git remote add origin $URL
              git fetch origin $REVISION
              git checkout FETCH_HEAD
              git log -1
              for arch in ${archs}; do
                V=1 TANG_OPERATOR_CI=1 GOOS=$(go env GOOS) GOARCH=$arch GOPATH=$(go env GOPATH) make build || exit $?
              done
              exit 0
